---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Example task
      ansible.builtin.debug:
        msg: "Python is installed and working!"
    - name: Install Python
      raw: |
        sudo apt update && sudo apt install -y python3
      changed_when: false
    - name: Ensure Python is installed
      ansible.builtin.raw: python3 --version
    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    # Start and enable Docker service
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Add user to Docker group
    - name: Add user to Docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    # Create a directory for the application
    - name: Create application directory
      file:
        path: /home/azureuser/hello-world-app
        state: directory
        owner: azureuser
        group: azureuser

    # Copy the Dockerfile and index.html to the VM
    - name: Copy Dockerfile and index.html
      copy:
        src: "{{ item }}"
        dest: /home/azureuser/hello-world-app/
        owner: azureuser
        group: azureuser
      with_items:
        - Dockerfile
        - index.html

    # Build the Docker image
    - name: Build Docker image
      docker_image:
        name: hello-world-app
        build:
          path: /home/azureuser/hello-world-app/
        source: build

    # Stop and remove any existing container
    - name: Stop and remove existing container
      docker_container:
        name: hello-world-app
        state: absent

    # Run the Docker container
    - name: Run Docker container
      docker_container:
        name: hello-world-app
        image: hello-world-app
        state: started
        ports:
          - "80:80"  # Expose port 80 on the VM




